# Generated by Django 4.1.7 on 2023-02-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='date_creation',
        ),
    ]
