# Generated by Django 4.1.7 on 2023-02-28 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_restaurant_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 23, 53, 33, 743431)),
        ),
    ]
