# Generated by Django 4.1.7 on 2023-02-28 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_restaurant_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
